version: "3"
services:
  nacos:
    hostname: nacos
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
    - PREFER_HOST_MODE=hostname
    - MODE=standalone
    ports:
    - "8848:8848"
  frontend:
    image: frontend:1.0.0-SNAPSHOT
    container_name: frontend
    environment:
    - dubbo.registry.address=nacos://nacos:8848
    - service.product.url=http://productservice:8082
    ports:
    - "8080:8080"
    depends_on:
      - "nacos"
  cartservice:
    image: cartservice:1.0.0-SNAPSHOT
    container_name: cartservice
    environment:
    - dubbo.registry.address=nacos://nacos:8848
    depends_on:
      - "nacos"
  productservice:
    image: productservice:1.0.0-SNAPSHOT
    container_name: productservice
